# This is a basic workflow to help you get started with Actions

name: NOTEBOOK-DEMO

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  dev_stage:
    runs-on: ubuntu-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:     
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # - name: Install Python packages
      #   run: pip install -r requirements.txt
      
      - uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: "config.toml"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          
          PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PASSPHRASE }} 
          SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR: ${{ vars.SNOWFLAKE_AUTHENTICATOR }}
          SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: ${{ vars.SNOWFLAKE_USER }}
          SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}

          SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}

        run: |
          
          snow --version
          snow connection test
          pwd
          ls -lrt
          snow notebook deploy Dim_table_A --replace
          snow notebook deploy Dim_table_B --replace
          snow notebook deploy Data_Processing_NB --replace
          
        

  qa_stage:
    runs-on: ubuntu-latest
    needs: dev_stage
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:     
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # - name: Install Python packages
      #   run: pip install -r requirements.txt
      
      - uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: "config.toml"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          
          PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PASSPHRASE }} 
          SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR: ${{ vars.SNOWFLAKE_AUTHENTICATOR }}
          SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: ${{ vars.SNOWFLAKE_USER }}
          SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}

          SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}

        run: |
          
          snow --version
          snow connection test
          pwd
          ls -lrt
          snow notebook deploy Dim_table_A --replace
          snow notebook deploy Dim_table_B --replace
          snow notebook deploy Data_Processing_NB --replace

  prod_stage:
    runs-on: ubuntu-latest
    needs: qa_stage
    environment: dev
    if: github.ref == 'refs/heads/main'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:     

    - uses: actions/checkout@v4

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # - name: Install Python packages
    #   run: pip install -r requirements.txt
    
    - uses: Snowflake-Labs/snowflake-cli-action@v1.5
      with:
        cli-version: "latest"
        default-config-file-path: "config.toml"

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      env:
        
        PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PASSPHRASE }} 
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR: ${{ vars.SNOWFLAKE_AUTHENTICATOR }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: ${{ vars.SNOWFLAKE_USER }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}

        SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}

      run: |
        
        snow --version
          snow connection test
          pwd
          ls -lrt
          snow notebook deploy Dim_table_A --replace
          snow notebook deploy Dim_table_B --replace
          snow notebook deploy Data_Processing_NB --replace

